# Generated by Django 4.2.20 on 2025-10-16 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('sales_staff', 'Sales Staff')], default='sales_staff', help_text='Account type: Super Admin or Sales Staff', max_length=20)),
                ('staff_type', models.CharField(choices=[('employee', 'Employee'), ('contractor', 'Contractor')], default='employee', help_text='Staff type: Employee or Contractor', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable if employee is currently active')),
                ('is_resigned', models.BooleanField(default=False, help_text='Mark if employee has resigned')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('other', 'Other')], default='mr', help_text='Title: Mr, Mrs, Miss, Ms, Other', max_length=10)),
                ('first_name', models.CharField(help_text="Employee's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Employee's last name", max_length=100)),
                ('email', models.EmailField(help_text="Employee's email address", max_length=254, unique=True)),
                ('password', models.CharField(help_text="Employee's password (will be hashed)", max_length=128)),
                ('position', models.CharField(blank=True, help_text="Employee's position/title", max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', help_text="Employee's gender", max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text="Employee's date of birth", null=True)),
                ('mobile_no', models.CharField(blank=True, help_text="Employee's mobile number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('landline_no', models.CharField(blank=True, help_text="Employee's landline number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('language_spoken', models.CharField(blank=True, help_text='Languages spoken by employee', max_length=200, null=True)),
                ('unit_number', models.CharField(blank=True, help_text='Unit/Apartment number', max_length=50, null=True)),
                ('address', models.TextField(blank=True, help_text="Employee's full address", null=True)),
                ('post_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True)),
                ('profile_image', models.TextField(blank=True, help_text="Employee's profile image as Base64 string", null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes visible only to administrators', null=True)),
                ('hours_per_week', models.PositiveIntegerField(blank=True, help_text='Weekly contracted hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Emergency contact's name", max_length=100)),
                ('relationship', models.CharField(help_text='Relationship to employee (e.g., Spouse, Parent, Sibling)', max_length=50)),
                ('phone', models.CharField(help_text="Emergency contact's phone number", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text="Emergency contact's email address", max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text="Emergency contact's address", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'emergency_contacts',
                'ordering': ['name'],
            },
        ),
    ]
