# Generated by Django 4.2.20 on 2025-10-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of field changes {field: {from: value, to: value}}')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who performed the change (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_history_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee this history entry pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee History',
                'verbose_name_plural': 'Employee History',
                'db_table': 'employee_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
