# Generated by Django 4.2.20 on 2025-10-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read')], max_length=10),
        ),
    ]
