# Generated by Django 4.2.20 on 2025-10-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeehistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text="Employee's email address", max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('email',)},
        ),
    ]
