# Generated by Django 4.2.20 on 2025-10-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_email_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text="Employee's email address", max_length=254, unique=True),
        ),
    ]
