# Generated by Django 4.2.25 on 2025-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
    ]
