# Generated by Django 4.2.25 on 2025-11-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_emergencycontact_is_deleted_employee_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Emergency Contact', 'verbose_name_plural': 'Emergency Contacts'},
        ),
    ]
