# Generated by Django 4.2.25 on 2025-11-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('employee', '0008_alter_emergencycontact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role assigned to this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='role.role'),
        ),
    ]
