# Generated by Django 4.2.25 on 2025-11-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_ensure_role_id_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('sales_staff', 'Sales Staff')], help_text='Account type: Super Admin or Sales Staff', max_length=20, null=True),
        ),
    ]
