# Generated by Django 4.2.25 on 2025-11-14 09:55

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Employee's profile image", null=True, upload_to=employee.models.employee_profile_image_upload_path),
        ),
    ]
