# Generated by Django 4.2.25 on 2025-11-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='role_permission_module_action_unique',
        ),
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='role_rolepermission_role_permission_unique',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
