# Generated by Django 4.2.25 on 2025-11-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_mobile_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of secondary mobile numbers (E.164 strings)', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_mobile_phone_code',
            field=models.JSONField(blank=True, default=list, help_text='Country codes aligned with each secondary mobile number', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_mobile_type',
            field=models.CharField(blank=True, choices=[('technical contact', 'Technical Contact'), ('financial contact', 'Financial Contact'), ('hr contact', 'HR Contact'), ('support contact', 'Support Contact'), ('sales contact', 'Sales Contact'), ('additional contact', 'Additional Contact')], help_text='Type label applied to the secondary contacts', max_length=32, null=True),
        ),
    ]
