# Generated by Django 4.2.25 on 2025-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_mobile_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='secondary_mobile_type',
            field=models.JSONField(blank=True, choices=[('technical contact', 'Technical Contact'), ('financial contact', 'Financial Contact'), ('hr contact', 'HR Contact'), ('support contact', 'Support Contact'), ('sales contact', 'Sales Contact'), ('additional contact', 'Additional Contact')], default=list, help_text='List of secondary mobile types', null=True),
        ),
    ] 
