# Generated by Django 4.2.25 on 2025-12-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_secondary_mobile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activity_notes',
            field=models.TextField(blank=True, help_text='Activity notes', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, help_text='Follow up date and time', null=True),
        ),
    ]
