# Generated by Django 4.2.25 on 2025-11-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='child_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_subtask_of', to='task.task'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task'),
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('parent_task', 'child_task')},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='title',
        ),
    ]
