# Generated by Django 4.2.25 on 2025-11-05 03:29

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_subtask_child_task_subtask_parent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=task.models.task_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='data_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
