# Generated by Django 4.2.25 on 2025-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskattachment_file_taskattachment_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('assign', 'Assign'), ('status_change', 'Status Change'), ('priority_change', 'Priority Change'), ('title_change', 'Title Change'), ('description_change', 'Description Change'), ('due_date_change', 'Due Date Change'), ('due_time_change', 'Due Time Change'), ('subtask_change', 'Subtask Change'), ('subtask_delete', 'Subtask Delete'), ('reminder_change', 'Reminder Change'), ('attachment_change', 'Attachment Change'), ('comment', 'Comment'), ('attachment_add', 'Attachment Added'), ('attachment_remove', 'Attachment Removed'), ('reminder_set', 'Reminder Set'), ('delete', 'Delete')], max_length=20),
        ),
    ]
