# Generated by Django 4.2.20 on 2025-10-16 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('other', 'Other')], default='mr', help_text='Title: Mr, Mrs, Miss, Ms, Other', max_length=10)),
                ('first_name', models.CharField(help_text="Lead's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Lead's last name", max_length=100)),
                ('company_name', models.CharField(help_text='Company name', max_length=200)),
                ('contact_number', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_address', models.EmailField(help_text='Primary email address', max_length=254)),
                ('custom_email_addresses', models.TextField(blank=True, help_text='Additional email addresses (comma-separated)', null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', null=True)),
                ('event', models.CharField(blank=True, help_text='Associated event', max_length=200, null=True)),
                ('lead_type', models.CharField(choices=[('exhibitor', 'Exhibitor'), ('sponsor', 'Sponsor'), ('visitor', 'Visitor')], default='exhibitor', help_text='Type of lead: Exhibitor, Sponsor, Visitor', max_length=20)),
                ('booth_size', models.CharField(blank=True, help_text='Booth size preference', max_length=100, null=True)),
                ('sponsorship_type', models.CharField(blank=True, help_text='Type of sponsorship', max_length=100, null=True)),
                ('registration_groups', models.CharField(blank=True, help_text='Registration groups', max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('info_pack', 'Info Pack'), ('attempted_contact', 'Attempted Contact'), ('contacted', 'Contacted'), ('contract_invoice_sent', 'Contract & Invoice Sent'), ('contract_signed_paid', 'Contract Signed & Paid'), ('withdrawn', 'Withdrawn'), ('lost', 'Lost'), ('converted', 'Converted'), ('future', 'Future')], default='new', help_text='Current lead status', max_length=30)),
                ('intensity', models.CharField(choices=[('cold', 'Cold Lead'), ('warm', 'Warm Lead'), ('hot', 'Hot Lead'), ('sql', 'Sales Qualified Lead (SQL)')], default='cold', help_text='Lead intensity level', max_length=20)),
                ('opportunity_price', models.DecimalField(blank=True, decimal_places=2, help_text='Opportunity price/value', max_digits=10, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags (comma-separated)', max_length=500, null=True)),
                ('how_did_you_hear', models.CharField(blank=True, help_text='How did they hear about us', max_length=200, null=True)),
                ('reason_for_enquiry', models.TextField(blank=True, help_text='Reason for enquiry', null=True)),
                ('assigned_sales_staff', models.CharField(blank=True, help_text='Assigned sales staff member', max_length=200, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True, help_text='Date when lead was received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-date_received'],
            },
        ),
    ]
