# Generated by Django 4.2.20 on 2025-10-16 06:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changed_by', models.CharField(blank=True, help_text='Actor performing change if known', max_length=200, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(help_text='Lead this history entry pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='lead.lead')),
            ],
            options={
                'verbose_name': 'Lead History',
                'verbose_name_plural': 'Lead History',
                'db_table': 'lead_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
