# Generated by Django 4.2.20 on 2025-10-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_leadhistory_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('email_address',)},
        ),
    ]
