# Generated by Django 4.2.20 on 2025-10-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
    ]
