# Generated by Django 4.2.25 on 2025-10-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_leadtag_registrationgroup_sponsorshiptype'),
    ]

    operations = [
        # First, clear any problematic data in the CharFields using raw SQL
        # This sets all string values to NULL before converting to ForeignKey
        migrations.RunSQL(
            sql="UPDATE leads SET registration_groups = NULL, sponsorship_type = NULL, tags = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Then convert CharField to ForeignKey
        migrations.AlterField(
            model_name='lead',
            name='registration_groups',
            field=models.ForeignKey(blank=True, help_text='Selected registration group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lead.registrationgroup'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sponsorship_type',
            field=models.ForeignKey(blank=True, help_text='Selected sponsorship type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lead.sponsorshiptype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ForeignKey(blank=True, help_text='Selected lead tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lead.leadtag'),
        ),
    ]
