# Generated by Django 4.2.25 on 2025-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_lead_registration_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='registration_groups',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sponsorship_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tags',
        ),
        migrations.AddField(
            model_name='lead',
            name='registration_groups',
            field=models.ManyToManyField(blank=True, help_text='Selected registration group', related_name='leads', to='lead.registrationgroup'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sponsorship_type',
            field=models.ManyToManyField(blank=True, help_text='Selected sponsorship type', related_name='leads', to='lead.sponsorshiptype'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Selected lead tag', related_name='leads', to='lead.leadtag'),
        ),
    ]
