# Generated by Django 4.2.25 on 2025-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_remove_lead_registration_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_business',
            field=models.CharField(blank=True, help_text='Lead business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_name',
            field=models.CharField(blank=True, help_text='Lead name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_pipeline',
            field=models.CharField(blank=True, help_text='Lead pipeline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_stage',
            field=models.CharField(blank=True, help_text='Lead stage', max_length=200, null=True),
        ),
    ]
