# Generated by Django 4.2.25 on 2025-11-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_lead_business_lead_lead_name_lead_lead_pipeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_business',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(blank=True, help_text='Lead type', max_length=200, null=True),
        ),
    ]
