# Generated by Django 4.2.25 on 2025-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_remove_lead_lead_business_alter_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AddField(
            model_name='leadtag',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AddField(
            model_name='registrationgroup',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AddField(
            model_name='sponsorshiptype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('exhibitor', 'Exhibitor'), ('sponsor', 'Sponsor'), ('visitor', 'Visitor')], default='exhibitor', help_text='Type of lead: Exhibitor, Sponsor, Visitor', max_length=20),
        ),
    ]
