# Generated by Django 4.2.25 on 2025-11-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_lead_is_deleted_leadhistory_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('attendee', 'Attendee'), ('job_leads', 'Job Leads'), ('info_pack', 'Info Pack'), ('attempted_contact', 'Attempted Contact'), ('contacted', 'Contacted'), ('contract_signed', 'Contract Signed'), ('contract_invoice_sent', 'Contract & Invoice Sent'), ('contract_signed_paid', 'Contract Signed & Paid'), ('withdrawn', 'Withdrawn'), ('lost', 'Lost'), ('converted', 'Converted'), ('future', 'Future')], default='new', help_text='Current lead status', max_length=30),
        ),
    ]
