# Generated by Django 4.2.25 on 2025-11-05 06:15

from django.db import migrations, models
import django.db.models.deletion


def migrate_assigned_sales_staff_data(apps, schema_editor):
    """
    Migrate assigned_sales_staff from CharField (string) to ForeignKey (integer)
    This function:
    1. Sets empty strings to NULL
    2. Attempts to match existing string names to Employee records
    3. Sets unmatched values to NULL
    """
    Lead = apps.get_model('lead', 'Lead')
    Employee = apps.get_model('employee', 'Employee')
    
    # First, set all empty strings to NULL using raw SQL
    schema_editor.execute(
        "UPDATE leads SET assigned_sales_staff = NULL WHERE assigned_sales_staff = '' OR assigned_sales_staff IS NULL"
    )
    
    # Get all leads with non-empty assigned_sales_staff
    leads = Lead.objects.exclude(assigned_sales_staff__isnull=True).exclude(assigned_sales_staff='')
    
    for lead in leads:
        staff_name = lead.assigned_sales_staff
        if not staff_name:
            continue
        
        # Try to find matching employee by name
        employee = None
        parts = str(staff_name).strip().split()
        
        if len(parts) >= 2:
            # Try exact match on first_name and last_name
            employee = Employee.objects.filter(
                first_name__iexact=parts[0],
                last_name__iexact=' '.join(parts[1:])
            ).first()
            
            # If not found, try partial match
            if not employee:
                employee = Employee.objects.filter(
                    first_name__icontains=parts[0],
                    last_name__icontains=parts[-1]
                ).first()
        else:
            # Single name - try first_name or last_name
            employee = Employee.objects.filter(
                first_name__iexact=str(staff_name)
            ).first()
            if not employee:
                employee = Employee.objects.filter(
                    last_name__iexact=str(staff_name)
                ).first()
        
        # If employee found, we'll need to store it temporarily
        # Since we can't set ForeignKey yet, we'll use raw SQL to set a temporary field
        # But actually, we need to add a temporary integer field first
        # Let's use a different approach: just set to NULL for now
        # The user can manually reassign after migration
        if employee:
            # Store the employee ID in a way we can use later
            # For now, we'll set it to NULL and let the user reassign
            # Or we can use raw SQL to directly update the field after we add the temp field
            pass
    
    # Set all existing string values to NULL since we can't directly convert
    # The user will need to reassign leads after migration
    schema_editor.execute(
        "UPDATE leads SET assigned_sales_staff = NULL WHERE assigned_sales_staff IS NOT NULL AND assigned_sales_staff != ''"
    )


def reverse_migrate_assigned_sales_staff_data(apps, schema_editor):
    """
    Reverse migration - convert ForeignKey back to string (not really possible to restore names)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_emergencycontact_options'),
        ('lead', '0012_alter_lead_status'),
    ]

    operations = [
        # Step 1: Clean up the data - set empty strings to NULL
        migrations.RunSQL(
            sql="UPDATE leads SET assigned_sales_staff = NULL WHERE assigned_sales_staff = '' OR assigned_sales_staff IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Set all existing string values to NULL (we can't match them automatically during migration)
        # This is safer - the user can reassign leads after migration if needed
        migrations.RunSQL(
            sql="UPDATE leads SET assigned_sales_staff = NULL WHERE assigned_sales_staff IS NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: Alter the field type from CharField to ForeignKey
        migrations.AlterField(
            model_name='lead',
            name='assigned_sales_staff',
            field=models.ForeignKey(blank=True, help_text='Assigned sales staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='employee.employee'),
        ),
    ]
