# Generated by Django 4.2.25 on 2025-11-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('lead', '0013_alter_lead_assigned_sales_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked customer (created or existing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer'),
        ),
    ]
