# Generated by Django 4.2.25 on 2025-11-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_lead_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-date_received'], 'permissions': [('can_use_duplicate_lead_email', 'Can create/update leads when email already exists')], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
