# Generated by Django 4.2.25 on 2025-11-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_alter_lead_booth_size_alter_lead_lead_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='event',
            field=models.CharField(blank=True, choices=[('Aged & Disability Expo', 'Aged & Disability Expo'), ('Aged & Disability Expo Adelaide', 'Aged & Disability Expo Adelaide'), ('Aged & Disability Expo Burnie', 'Aged & Disability Expo Burnie'), ('Aged & Disability Expo Devonport', 'Aged & Disability Expo Devonport'), ('Aged & Disability Expo Gold Coast', 'Aged & Disability Expo Gold Coast'), ('Aged & Disability Expo Gold Coast 2026', 'Aged & Disability Expo Gold Coast 2026'), ('Aged & Disability Expo Hobart', 'Aged & Disability Expo Hobart'), ('Aged & Disability Expo Launceston', 'Aged & Disability Expo Launceston')], default='Aged & Disability Expo', help_text='Associated event', max_length=200, null=True),
        ),
    ]
