# Generated by Django 4.2.25 on 2025-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled'), ('starred', 'Starred'), ('trash', 'Trash')], default='draft', max_length=10),
        ),
    ]
