# Generated by Django 4.2.25 on 2025-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled'), ('trash', 'Trash')], default='draft', max_length=10),
        ),
    ]
