# Generated by Django 4.2.25 on 2025-11-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mail_is_starred_alter_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
