# Generated by Django 4.2.25 on 2025-11-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_profile_image'),
        ('mail', '0005_mail_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='owner',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to='employee.employee'),
        ),
    ]
