# Generated by Django 4.2.25 on 2025-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_profile_image'),
        ('mail', '0006_rename_owner_mail_sender_mail_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='receiver',
        ),
        migrations.AddField(
            model_name='mail',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='received_mails', to='employee.employee'),
        ),
    ]
