# Generated by Django 4.2.25 on 2025-11-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_profile_image'),
        ('mail', '0007_remove_mail_receiver_mail_receivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_starred',
        ),
        migrations.CreateModel(
            name='MailParticipantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('delete_status', models.CharField(choices=[('sent', 'Sent'), ('inbox', 'Inbox'), ('trash', 'Trash'), ('deleted', 'Deleted (softdelete)')], default='inbox', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_statuses', to='employee.employee')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_statuses', to='mail.mail')),
            ],
            options={
                'db_table': 'mail_participant_statuses',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['mail', 'employee'], name='mail_partic_mail_id_e232bc_idx'), models.Index(fields=['employee', 'is_read'], name='mail_partic_employe_401d51_idx'), models.Index(fields=['employee', 'is_starred'], name='mail_partic_employe_92270b_idx'), models.Index(fields=['employee', 'delete_status'], name='mail_partic_employe_841c1b_idx')],
                'unique_together': {('mail', 'employee')},
            },
        ),
    ]
