# Generated by Django 4.2.25 on 2025-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_alter_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='template',
            field=models.CharField(choices=[('dea_crm', 'DEA CRM')], default='dea_crm', help_text='Which email template to use when sending (e.g. default, DEA CRM)', max_length=50),
        ),
    ]
