# Generated by Django 4.2.25 on 2025-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_mail_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='template',
        ),
        migrations.AddField(
            model_name='mail',
            name='templates',
            field=models.JSONField(blank=True, default=list, help_text="List of template keys to use when sending (e.g. ['dea_crm'])"),
        ),
    ]
