# Generated by Django 4.2.25 on 2025-11-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_remove_mail_template_mail_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='templates',
            field=models.JSONField(blank=True, default=list, help_text="List of template keys to use when sending (e.g. ['template_1'])"),
        ),
    ]
