# Generated by Django 4.2.25 on 2025-11-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_alter_mail_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
