# Generated by Django 4.2.25 on 2025-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_alter_mail_body_alter_mail_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='templates',
        ),
        migrations.AddField(
            model_name='mail',
            name='template',
            field=models.CharField(blank=True, choices=[('Template 1', 'Template 1'), ('Template 2', 'Template 2'), ('Template 3', 'Template 3'), ('Template 4', 'Template 4'), ('Template 5', 'Template 5')], default='Template 1', help_text='Template to use when sending', max_length=255),
        ),
    ]
