# Generated by Django 4.2.25 on 2025-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_remove_mail_templates_mail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='template',
            field=models.CharField(blank=True, choices=[('Template 1', 'Template 1'), ('Template 2', 'Template 2'), ('Template 3', 'Template 3'), ('Template 4', 'Template 4'), ('Template 5', 'Template 5')], help_text='Template to use when sending', max_length=255, null=True),
        ),
    ]
