# Generated by Django 4.2.25 on 2025-11-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_alter_emergencycontact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('lead_assignment', 'Lead Assignment'), ('task_assignment', 'Task Assignment'), ('task_reminder', 'Task Reminder')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lead_id', models.PositiveIntegerField(blank=True, help_text='Related lead ID if notification type is lead_assignment', null=True)),
                ('task_id', models.PositiveIntegerField(blank=True, help_text='Related task ID if notification type is task_assignment or task_reminder', null=True)),
                ('reminder_id', models.PositiveIntegerField(blank=True, help_text='Related reminder ID if notification type is task_reminder', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employee.employee')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx')],
            },
        ),
    ]
